import Head from "next/head";
import { useState } from "react";

type ItemType = { name: string; price: number };

export default function Home() {
  const [items, setItems] = useState<ItemType[]>([
    { name: "Coffee", price: 100 },
    { name: "Movie", price: 200 },
    { name: "Candy", price: 300 },
  ]);

  const [total, setTotal] = useState(0);

  return (
    <>
      <Head>
        <title>Expense tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-black to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Expense Tracker
          </h1>
          <div className="flex flex-col gap-4 rounded-xl bg-white/10 p-4 text-white">
            <form className="grid grid-cols-6 gap-4 text-black">
              <input
                className="col-span-3 rounded border p-3"
                type="text"
                name=""
                id=""
                placeholder="Enter item"
              />
              <input
                className="col-span-2 rounded border p-3"
                type="number"
                name=""
                id=""
                placeholder="Enter price"
              />
              <button
                className="bg-slate-950 p-3 text-white hover:bg-slate-900"
                type="submit"
              >
                +
              </button>
            </form>
            {items.length > 0 && (
              <>
                <ul>
                  {items.map((item, id) => {
                    return (
                      <li
                        key={id}
                        className="border-b-2 border-white/10 bg-slate-950 last:border-b-0"
                      >
                        <div className="grid grid-cols-6 gap-4">
                          <span className="col-span-3 p-3 capitalize">
                            {item.name}
                          </span>
                          <span className="col-span-2 p-3 text-center">
                            {item.price}
                          </span>
                          <button className="border-l-2 border-white/10 bg-slate-950 p-3 text-white hover:bg-slate-900">
                            -
                          </button>
                        </div>
                      </li>
                    );
                  })}
                </ul>
                <div className="flex justify-between p-3">
                  <span>Total:</span>
                  <span>{total}</span>
                </div>
              </>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
